baseURL = 'https://wiki.shreyanjain.net/'
languageCode = 'en-us'
title = 'wiki.shreyanjain.net'
enableGitInfo = true
disableKinds = ["taxonomy", "term"]

[markup.tableOfContents]
startLevel = 2
endLevel = 6

[markup.goldmark.renderer]
unsafe = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[outputs]
home = ["HTML", "JSON"]
section = ["HTML"]
page = ["HTML"]

[params]
use_titles_in_section_lists = false
